// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/4/2025, 7:36:20 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/workspace/FABLECRAFT NUXT BUILD/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/FABLECRAFT NUXT BUILD/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/FABLECRAFT NUXT BUILD/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/FABLECRAFT NUXT BUILD/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/FABLECRAFT NUXT BUILD/plugins/**/*.{js,ts,mjs}","/workspace/FABLECRAFT NUXT BUILD/composables/**/*.{js,ts,mjs}","/workspace/FABLECRAFT NUXT BUILD/utils/**/*.{js,ts,mjs}","/workspace/FABLECRAFT NUXT BUILD/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspace/FABLECRAFT NUXT BUILD/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspace/FABLECRAFT NUXT BUILD/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspace/FABLECRAFT NUXT BUILD/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;