-- Enable the pgvector extension for future use
create extension if not exists vector with schema extensions;

-- Create a table for user projects
create table projects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text,
  inserted_at timestamptz default now() not null
);

-- Set up Row Level Security for the projects table
alter table projects enable row level security;

create policy "Users can manage their own projects." on projects
  for all using (auth.uid() = user_id);